### PR TITLE
Show notifications from workers

### LINKED ISSUE #3754: Possible "pull" notification regression
With this (?) I get a regression for the notification worker (pull requests):

```
java.lang.IllegalStateException: Expedited WorkRequests require a Worker to provide an implementation for `getForegroundInfo()`
```

This is only visible in Logcat but prohibits notifications.

At the moment I cannot easily fix it (either by disabling the OneTimeWorkRequest or trying to move the NotificationWorker to a CoroutineWorker).

_Originally posted by @Lakoja in https://github.com/tuskyapp/Tusky/issues/3649#issuecomment-1594285314_

### PR DESCRIPTION
**Pull request by nikclayton**
Fix a crash where workers, in some conditions, should show a notification, but didn't.

These new notifications are sent to a dedicated channel with no importance.

Convert `NotificationWorker` to a `CoroutineWorker` and remove its use of `runBlocking`.

Fixes #3754

### CODE REVIEW

**Comment by nikclayton** [comment]
Might need a bit more work -- experimenting on an API 30 emulator, sometimes the "Fetching notifications..." notification is cancelled, sometimes it's not. Not sure why yet...

**Comment by Lakoja** [comment]
> Might need a bit more work -- experimenting on an API 30 emulator, sometimes the "Fetching notifications..." notification is cancelled, sometimes it's not. Not sure why yet...

Works ok in my tests for the moment.

However I was wondering (also earlier) about the `Thread.sleep` in the code. Shouldn't that be a `delay`?

**Comment by nikclayton** [comment]
> However I was wondering (also earlier) about the `Thread.sleep` in the code. Shouldn't that be a `delay`?

Yep, good catch. Fixed.

File: app/src/main/java/com/keylesspalace/tusky/worker/NotificationWorker.kt [hunk 1]
```diff
@@ -17,27 +17,36 @@
...
-    override fun doWork(): Result {
+) : CoroutineWorker(appContext, params) {
+    val notification: Notification = NotificationHelper.createWorkerNotification(applicationContext, R.string.notification_notification_worker)
+
+    override suspend fun doWork(): Result {
         notificationsFetcher.fetchAndShow()
         return Result.success()
     }
 
+    override suspend fun getForegroundInfo() = ForegroundInfo(NOTIFICATION_ID_FETCH_NOTIFICATION, notification)
```
[the remark this answers is not in the document]
Comment (nikclayton) [reply app/src/main/java/com/keylesspalace/tusky/worker/NotificationWorker.kt:44]: It works on Android 12 because `getForegroundInfo()` isn't called on Android 12, there `getForegroundInfoAsync()` is called instead, https://developer.android.com/reference/kotlin/androidx/work/CoroutineWorker#getForegroundInfo()

File: app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java [hunk 2]
```diff
@@ -121,6 +127,7 @@ public class NotificationHelper {
     public static final String CHANNEL_SIGN_UP = "CHANNEL_SIGN_UP";
     public static final String CHANNEL_UPDATES = "CHANNEL_UPDATES";
     public static final String CHANNEL_REPORT = "CHANNEL_REPORT";
+    public static final String CHANNEL_LISTENABLE_WORKER = "CHANNEL_LISTENABLE_WORKER";
```
Comment (Lakoja) [inline app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java:130]: CHANNEL_BACKGROUND_TASKS ? (listenable sound quite technical/specific)

**Review by Lakoja — APPROVED** [review]

File: app/src/main/java/com/keylesspalace/tusky/worker/PruneCacheWorker.kt [hunk 3]
```diff
@@ -41,6 +48,8 @@ class PruneCacheWorker(
         return Result.success()
     }
 
+    override suspend fun getForegroundInfo() = ForegroundInfo(NOTIFICATION_ID_PRUNE_CACHE, notification)
```
Comment (connyduck) [inline app/src/main/java/com/keylesspalace/tusky/worker/PruneCacheWorker.kt:51]: Why here as well? This one is not expedited?

File: app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java (hunk 2 above)
Comment (connyduck) [reply app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java:130]: agree

File: app/src/main/java/com/keylesspalace/tusky/worker/PruneCacheWorker.kt (hunk 3 above)
Comment (nikclayton) [reply app/src/main/java/com/keylesspalace/tusky/worker/PruneCacheWorker.kt:51]: Belt and braces. If future code launches this as an expedited worker it won't work without this.

But the failure will be effectively silent (there's no user notification that it happened), and unless you're (a) checking the logs when it happens, or (b) notice that the database is growing without bounds, it won't be noticed.

Comment (connyduck) [reply app/src/main/java/com/keylesspalace/tusky/worker/PruneCacheWorker.kt:51]: ok

File: app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java (hunk 2 above)
Comment (nikclayton) [reply app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java]: Done.

**Review by connyduck — APPROVED** [review]
