### PR TITLE
Material3 polishing

### LINKED ISSUE #4692: The screen after reporting an account shows loading circles over block / mute buttons
### Detailed description

Report someone then see the buttons that come up in the view that follows. There are loading circles going round over the text, in the same colour as the background so they're hard to see.

### Steps to reproduce the problem

_No response_

### Debug information

Tusky Test 26.2-f2a2c164

### PR DESCRIPTION
**Pull request by connyduck**
see commit messages for a list of changes

closes #4692

### CODE REVIEW

**Comment by connyduck** [comment]
should be done for now

**Comment by connyduck** [comment]
The biggest difference is probably how the help text looks now

Screenshot_20240915_170237

File: app/src/main/java/com/keylesspalace/tusky/components/report/fragments/ReportDoneFragment.kt [hunk 1]
```diff
@@ -49,11 +47,11 @@ class ReportDoneFragment : Fragment(R.layout.fragment_report_done) {
             viewModel.muteState.collect {
                 if (it == null) return@collect
                 if (it !is Loading) {
-                    binding.buttonMute.show()
-                    binding.progressMute.show()
+                    binding.buttonMute.visibility = View.VISIBLE
+                    binding.progressMute.visibility = View.GONE
```
Comment (Tak) [inline app/src/main/java/com/keylesspalace/tusky/components/report/fragments/ReportDoneFragment.kt:51]: Is it intentional to change the behavior here? Was it wrong?

**Review by Tak — APPROVED** [review]

File: app/src/main/java/com/keylesspalace/tusky/components/report/fragments/ReportDoneFragment.kt (hunk 1 above)
Comment (connyduck) [reply app/src/main/java/com/keylesspalace/tusky/components/report/fragments/ReportDoneFragment.kt:51]: Yes intentional because of two reasons:
- The `CircularProgressIndicator` has methods `show()` / `hide()` that don't do exactly what is expected, causing #4692 
- Setting the buttons to invisible instead of gone doesn't reflow the layout which is nicer

**Review by Tak — APPROVED** [review]
