### PR TITLE
Handle status edit histories with < 2 entries

### LINKED ISSUE #3743: App crashes upon trying to view edit history
Trying to view the edit history of [this post](https://spore.social/@tamarasiuda/110522895217050705) results in a crash.
Edit history is available when viewing on OP instance, but not when viewing remotely (see screenshot) which I assume is the source of the crash.
Screenshot_20230612-190544_Firefox

* * * *
- Tusky Version: 22.0
- Android Version: 12
- Android Device: Samsung Galaxy A12 
- Mastodon instance (if applicable): spore.social (posted), multiple (viewing)

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

### PR DESCRIPTION
**Pull request by nikclayton**
This can happen if the edit history has not been propogated to the user's server.

Try and fetch the edit history from the original poster's server. This may succeed (if the status was public). If it doesn't then show a specific error message.

Fixes #3743

### CODE REVIEW

**Comment by connyduck** [comment]
I'm very much against doing calls to instances other than the one the user logged in with.

- It breaks privacy. As a user I would definitely not approve my client to leak my IP address to foreign instances. Also we would have to change our [privacy policy](https://tusky.app/privacy-policy/).
- Malicious instances could probably exploit this somehow e.g. by making Tusky load 1000s of images.
- It only works with public posts on Mastodon Api compatible servers, but there are others
- Opens the door for other calls to foreign instances, and that is complexity I would very much like to keep out of our code

File: app/src/main/java/com/keylesspalace/tusky/components/viewthread/edits/ViewEditsFragment.kt [hunk 1]
```diff
@@ -86,6 +86,7 @@ class ViewEditsFragment :
         (binding.recyclerView.itemAnimator as SimpleItemAnimator).supportsChangeAnimations = false
 
         statusId = requireArguments().getString(STATUS_ID_EXTRA)!!
+
```
Comment (nikclayton) [inline app/src/main/java/com/keylesspalace/tusky/components/viewthread/edits/ViewEditsFragment.kt:89]:
```suggestion
```

**Comment by nikclayton** [comment]
OK. Updated to remove that feature and be more specific in the error message.

**Review by connyduck — APPROVED** [review]
