### PR TITLE
Account for underscores when tokenizing mentions for autocompletion

### LINKED ISSUE #743: Nicknames with underscore are not shown
While entering `@` followed with nickname, completion popup appears. 
With a nickname containing an underscore `_` completion is not working as expected 

* * * *
- Tusky Version: https://github.com/tuskyapp/Tusky/commit/eee48e48d1e0ec0fe9bd466fc4adbf895cdfb910
- Android Version:  OmniRom 8.1
- Android Device: xz1 compact
- Mastodon instance (if applicable): mstdn.fr (2.4.3)

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

Normal completion: 

Completion of `@sb_5` into tusky: 

Completion of `@sb_5` into firefox:

### PR DESCRIPTION
**Pull request by Tak**
Fixes #743

### CODE REVIEW

File: app/src/main/java/com/keylesspalace/tusky/util/MentionTokenizer.kt [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+            i--
+            character = if (i == 0) ' ' else text[i - 1]
+        }
+        if (i < 1 || character != '@') {
+            return cursor
+        }
+        return i
+    }
+
+    override fun findTokenEnd(text: CharSequence?, cursor: Int): Int {
```
Comment (connyduck) [inline app/src/main/java/com/keylesspalace/tusky/util/MentionTokenizer.kt]: the `Tokenizer` interface has no nullability annotations, but I am pretty sure it is save to make it non-null

File: app/src/main/java/com/keylesspalace/tusky/util/MentionTokenizer.kt [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+            if (text[i] == ' ') {
+                return i
+            } else {
+                i++
+            }
+        }
+        return length
+    }
+
+    override fun terminateToken(text: CharSequence?): CharSequence {
```
Comment (connyduck) [inline app/src/main/java/com/keylesspalace/tusky/util/MentionTokenizer.kt]: here as well
