### PR TITLE
keep ordering when picking multiple media files at once

### LINKED ISSUE #4754: When attaching multiple images at once, they appear in random order
### Steps to reproduce the problem

1. Start composing a post
2. Click paperclip, "add media"
3. In the image selector, longpress four images, tap "select"

**Expected behavior:** The four images appear in the post in the order I longpressed them

**Observed behavior:** The four images appear in what appears to be literally random order. It's not chronological.

This significantly slows down making posts with many images, because on my phone I have to do multiple clicks to get into the Photos app and then that is multiplied by four due to this bug.

Odd point for comparison: In my testing it appears the bluesky social app **does** have this problem and Discord **does not**. The fact Discord does not have the problem makes me suspect the problem is in the app and not in Android.

### Debug information

Tusky 26.2
"Version: 4.4.0-nightly.2024-11-06"
Android 13
Sony Xperia 5 III
mastodon.social

However, also @connyduck reports he saw this.

### PR DESCRIPTION
**Pull request by connyduck**
This restructures the code so that all picked media will be added to the upload queue in the correct order and also does some other code cleanup.

closes #4754

### CODE REVIEW

File: app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt [hunk 1]
```diff
@@ -162,7 +164,11 @@ class ComposeActivity :
     private val takePictureLauncher =
         registerForActivityResult(ActivityResultContracts.TakePicture()) { success ->
             if (success) {
-                pickMedia(photoUploadUri!!)
+                viewModel.pickMedia(
+                    listOf(
+                        ComposeViewModel.PickedMedia(photoUploadUri!!)
+                    )
+                )
             }
```
Comment (Lakoja) [inline app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt:172]: else - is that possible?

File: app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt [hunk 2]
```diff
@@ -588,6 +578,36 @@ class ComposeViewModel @Inject constructor(
...
+        }
+        enum class State {
+            UPLOADING,
+            UNPROCESSED,
+            PROCESSED,
+            PUBLISHED
+        }
+    }
+
+    data class PickedMedia(
```
Comment (Lakoja) [inline app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt:606]: Naming: Is it important that it is "picked" here? Or more like "LocalMedia" or somesuch.

File: app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt [hunk 3]
```diff
@@ -505,11 +497,9 @@ class ComposeViewModel @Inject constructor(
...
         if (draftAttachments != null) {
             // when coming from DraftActivity
-            viewModelScope.launch {
-                draftAttachments.forEach { attachment ->
-                    pickMedia(attachment.uri, attachment.description, attachment.focus)
-                }
-            }
+            draftAttachments.map { attachment ->
+                PickedMedia(attachment.uri, attachment.description, attachment.focus)
+            }.let { pickMedia(it) }
```
Comment (Lakoja) [inline app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt:502]: Is "it" a list here?

File: app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt [hunk 4]
```diff
@@ -347,14 +353,14 @@ class ComposeActivity :
                     when (intent.action) {
                         Intent.ACTION_SEND -> {
                             intent.getParcelableExtraCompat<Uri>(Intent.EXTRA_STREAM)?.let { uri ->
-                                pickMedia(uri)
+                                viewModel.pickMedia(listOf(ComposeViewModel.PickedMedia(uri)))
```
Comment (Lakoja) [inline app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt:356]: Overload "pickMedia"? There are three usages with only an uri here.

File: app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt (hunk 1 above)
Comment (connyduck) [reply app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt:172]: I think that is mostly when users cancel. And when the camera fails I'd expect the camera app to show an error 🤔

File: app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt (hunk 3 above)
Comment (connyduck) [reply app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt:502]: yes

File: app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt (hunk 2 above)
Comment (Lakoja) [reply app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt:608]: MediaData?

**Review by Lakoja — APPROVED** [review]
