### PR TITLE
fix loading posts with invalid `published_at` in preview card

### LINKED ISSUE #4992: Trending posts no longer load
Trending posts stopped loading in the beta.  They still load fine in browser for my instance 

App details:

Tusky 28.0 beta 1

Device:

asus ASUS_AI2401_H
Android version: 15
SDK version: 35

Account:

@vwbusguy@mastodon.online
Version: 4.4.0-nightly.2025-03-14-security

### PR DESCRIPTION
**Pull request by connyduck**
closes #4992

### CODE REVIEW

**Comment by cbeyls** [comment]
I don't have access to my computer today, but you should reimplement GuardedAdapter to use peekJson() and provide the peeked reader to the Delegate adapter, then call skip. That way the Delegate can crash at any point in the peeked stream, it doesn't matter because we always where we are in the original stream.
I already wrote this, I can send you the code this evening or tomorrow if you want to.

**Comment by connyduck** [comment]
@cbeyls I think I figured it out, thank you very much for the help!

**Comment by cbeyls** [comment]
You're welcome, that should do the trick yes. I will still check later if my code had any extra logic.

File: app/src/main/java/com/keylesspalace/tusky/json/GuardedAdapter.kt [hunk 1]
```diff
@@ -35,10 +35,11 @@ class GuardedAdapter<T> private constructor(
 
     override fun fromJson(reader: JsonReader): T? {
         return try {
-            delegate.fromJson(reader)
+            delegate.fromJson(reader.peekJson())
```
Comment (cbeyls) [inline app/src/main/java/com/keylesspalace/tusky/json/GuardedAdapter.kt:38]: I recommend you close the peeked reader after usage so the Okio buffer segments can move back to the pool:
`reader.peekJson().use { delegate.fromJson(it) }`

File: app/src/main/java/com/keylesspalace/tusky/json/GuardedAdapter.kt [hunk 2]
```diff
@@ -35,10 +35,11 @@ class GuardedAdapter<T> private constructor(
...
         } catch (e: JsonDataException) {
```
Comment (cbeyls) [inline app/src/main/java/com/keylesspalace/tusky/json/GuardedAdapter.kt:39]: You should probably catch all kinds of exceptions, not just `JsonDataException`.
`JsonDataException` is what Moshi itself and its official adapters throw but you may have other unhandled exceptions like `IllegalArgumentException` in your own custom adapters.

**Comment by cbeyls** [comment]
I compared with my own implementation and the 2 comments I left in the review are the only differences I found.
