### PR TITLE
Fix deserialization of the response from friendica on api/v2/instance

### LINKED ISSUE #4100: [friendica] Post length limited to 500 in recent Friendica RC
Using Tusky Test 23.0-e9195846 with Friendica 2023.09-rc on loma.ml, I noticed that all of a sudden I can't compose posts longer than 500 chars anymore. Current Tusky stable does however display the "correct" amount of chars allowed per post (around 20k on that instance). Any way to fix this?

### PR DESCRIPTION
**Pull request by Tak**
Fixes #4100

### CODE REVIEW

File: app/src/test/java/com/keylesspalace/tusky/components/compose/ComposeActivity/ComposeActivityTest.kt [hunk 1]
```diff
@@ -591,4 +602,83 @@ class ComposeActivityTest {
...
+            "    },\n" +
+            "    \"rules\": [\n" +
+            "    ],\n" +
+            "    \"friendica\": {\n" +
+            "        \"version\": \"2023.09-rc\",\n" +
+            "        \"codename\": \"Giant Rhubarb\",\n" +
+            "        \"db_version\": 1539\n" +
+            "    }\n" +
+            "}"
+    }
```
Comment (connyduck) [inline app/src/test/java/com/keylesspalace/tusky/components/compose/ComposeActivity/ComposeActivityTest.kt:683]:
```suggestion
        private val sampleFriendicaResponse = """{
                "domain": "loma.ml",
                "title": "[ˈloma]",
                "version": "2.8.0 (compatible; Friendica 2023.09-rc)",
                "source_url": "https://git.friendi.ca/friendica/friendica",
                "description": "loma.ml ist eine Friendica Community im Fediverse auf der vorwiegend DE \uD83C\uDDE9\uD83C\uDDEA gesprochen wird. \\r\\nServer in Germany/EU \uD83C\uDDE9\uD83C\uDDEA \uD83C\uDDEA\uD83C\uDDFA. Open to all with fun in new. \\r\\nServer in Deutschland. Offen für alle mit Spaß an Neuen.",
                "usage": {
                    "users": {
                        "active_month": 125
                    }
                },
                "thumbnail": {
                    "url": "https://loma.ml/ad/friendica-banner.jpg"
                },
                "languages": [
                    "de"
                ],
                "configuration": {
                    "statuses": {
                        "max_characters": $friendicaMaximum
                    },
                    "media_attachments": {
                        "supported_mime_types": {
                            "image/jpeg": "jpg",
                            "image/jpg": "jpg",
                            "image/png": "png",
                            "image/gif": "gif"
                        },
                        "image_size_limit": 10485760
                    }
                },
                "registrations": {
                    "enabled": true,
                    "approval_required": false
                },
                "contact": {
                    "email": "anony@miz.ed",
                    "account": {
                        "id": "9632",
                        "username": "webm",
                        "acct": "webm",
                        "display_name": "web m \uD83C\uDDEA\uD83C\uDDFA",
                        "locked": false,
                        "bot": false,
                        "discoverable": true,
                        "group": false,
                        "created_at": "2018-05-21T11:24:55.000Z",
                        "note": "\uD83C\uDDE9\uD83C\uDDEA Über diesen Account werden Änderungen oder geplante Beeinträchtigungen angekündigt. Wenn du einen Account auf Loma.ml besitzt, dann solltest du dich mit mir verbinden.\uD83C\uDDEA\uD83C\uDDFA Changes or planned impairments are announced via this account. If you have an account on Loma.ml, you should connect to me.\uD83C\uDD98 Fallbackaccount @webm@joinfriendica.de",
                        "url": "https://loma.ml/profile/webm",
                        "avatar": "https://loma.ml/photo/contact/320/373ebf56355ac895a09cb99264485383?ts=1686417730",
                        "avatar_static": "https://loma.ml/photo/contact/320/373ebf56355ac895a09cb99264485383?ts=1686417730&static=1",
                        "header": "https://loma.ml/photo/header/373ebf56355ac895a09cb99264485383?ts=1686417730",
                        "header_static": "https://loma.ml/photo/header/373ebf56355ac895a09cb99264485383?ts=1686417730&static=1",
                        "followers_count": 23,
                        "following_count": 25,
                        "statuses_count": 15,
                        "last_status_at": "2023-09-19T00:00:00.000Z",
                        "emojis": [],
                        "fields": []
                    }
                },
                "rules": [],
                "friendica": {
                    "version": "2023.09-rc",
                    "codename": "Giant Rhubarb",
                    "db_version": 1539
                }
            }
        """.trimIndent()  
    }
```

**Review by connyduck — APPROVED** [review]
