### PR TITLE
3419 alt text in any case

### LINKED ISSUE #3419: Slow image upload: alt text will be deleted
When composing:
If you add an image you can edit the description (alt text) while it uploads. If you finish your alt text before upload is finished, then this text will not be part of the published status.

Everything else seems to be correct however (for example the small description icon in the lower right of the preview image is blue).

Not sure if this is recent - maybe upload being slow is not so common that this problem could be present for a longer time.
But there are a number of issues that changed image upload code in the near past: For example #2479 or #2626.

* * * *
- Tusky Version: Recent develop (ce6a350)

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

Technical help:
"Slow" upload speed can easily be simulated by adding a wait at the end of the transfer here:

ProgressRequestBody#writeTo
`try { Thread.sleep(13000); } catch (InterruptedException ex) {}`

### PR DESCRIPTION
**Pull request by Lakoja**
Fixes #3419

### CODE REVIEW

File: app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt [hunk 1]
```diff
@@ -323,9 +323,8 @@ class ComposeViewModel @Inject constructor(
         serviceClient.sendToot(tootToSend)
     }
 
-    // Updates a QueuedMedia item arbitrarily, then sends description and focus to server
-    private suspend fun updateMediaItem(localId: Int, mutator: (QueuedMedia) -> QueuedMedia): Boolean {
-        val newMediaList = media.updateAndGet { mediaValue ->
+    private fun updateMediaItem(localId: Int, mutator: (QueuedMedia) -> QueuedMedia) {
+        media.updateAndGet { mediaValue ->
```
Comment (Lakoja) [inline app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt:327]: I have the feeling that this could be simplified even much further? Get rid of updateMediaItem and "updateAndGet"?

(Simply set the respective field - with a simple "find" before?)

File: app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt [hunk 2]
```diff
@@ -334,33 +333,16 @@ class ComposeViewModel @Inject constructor(
                 }
             }
         }
-
-        if (!editing) {
-            // Updates to media for already-published statuses need to go through the status edit api
```
Comment (Lakoja) [inline app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt:339]: I wonder if this comment was true even before?

With this new code (in StatusSendService) it also works when editing a status.

(maybe @mcclure ?)

File: app/src/main/java/com/keylesspalace/tusky/network/ProgressRequestBody.java [hunk 3]
```diff
@@ -67,8 +67,10 @@ public void writeTo(@NonNull BufferedSink sink) throws IOException {
                 uploaded += read;
                 sink.write(buffer, 0, read);
             }
+
+            uploadListener.onProgressUpdate((int)(100 * uploaded / contentLength));
```
Comment (Lakoja) [inline app/src/main/java/com/keylesspalace/tusky/network/ProgressRequestBody.java:71]: This fills the upload progress circle.

(But maybe the incomplete circle was intended as there seems to be some processing after it before the blue circle actually disappears?)

File: app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt [hunk 4]
```diff
@@ -181,6 +182,20 @@ class SendStatusService : Service(), Injectable {
...
 
+            media.forEach { mediaItem ->
+                if (mediaItem.processed) {
+                    val focus = mediaItem.focus
+                    val focusString = if (focus != null) "${focus.x},${focus.y}" else null
+                    Log.w(TAG, "updating media description on status send "+mediaItem.description )
+                    mastodonApi.updateMedia(mediaItem.id!!, mediaItem.description, focusString)
+                        .fold({
+                        }, { throwable ->
+                            Toast.makeText(applicationContext, R.string.error_failed_set_caption, Toast.LENGTH_SHORT).show()
```
Comment (Lakoja) [inline app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt:193]: The message/case now leaves out the "focus failed" message.

I guess the one here should be a more generic one (and the old two removed).

File: app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt (hunk 2 above)
Comment (mcclure) [reply app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt:339]: I don't recognize this code, sorry. The only advice I have is to make sure your change works when editing (cropping) an image (because that at some level deletes the image and replaces it with a new one)

Comment (Tak) [reply app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt:339]: It was _absolutely_ true before - without this codepath, when editing the caption of an attachment to an already-published status (post status with media attachment, edit status, edit caption of attachment), the user would get a popup about setting the caption failing

Comment (Tak) [reply app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt:339]: https://github.com/tuskyapp/Tusky/pull/3215#issuecomment-1407476422

File: app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt (hunk 4 above)
Comment (Tak) [reply app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt:193]: I believe that we prefer snackbars for these

Comment (Tak) [reply app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt:193]: This needs to be guarded with `!editing` like the previous block in `updateMediaItem` was, for the same reason. Testing locally, I hit the failure block here when editing the caption and focus for an attachment to a published status.

File: app/src/main/java/com/keylesspalace/tusky/network/ProgressRequestBody.java (hunk 3 above)
Comment (Tak) [reply app/src/main/java/com/keylesspalace/tusky/network/ProgressRequestBody.java:71]: Maybe move this unrelated change to a separate PR?

**Review by Tak — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt (hunk 2 above)
Comment (Tak) [reply app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt:339]: The description/focus *do* get updated, but because of the subsequent call to `editStatus`, not the `updateMedia` call here, which fails.

Comment (Lakoja) [reply app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt:339]: Very odd that the call to update media is then necessary initially.

But you are right.

Added "isEditing".

File: app/src/main/java/com/keylesspalace/tusky/network/ProgressRequestBody.java (hunk 3 above)
Comment (Lakoja) [reply app/src/main/java/com/keylesspalace/tusky/network/ProgressRequestBody.java:71]: It's such a small collateral fix. :-)

I could remove it.

File: app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt (hunk 4 above)
Comment (Lakoja) [reply app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt]: Re snackbar: That absolutely needs a view.

However this is a service so more or less the opposite.

Other errors are reported as actual notifications here.

So I'm not sure it should even show a Toast (but it probably doesn't hurt).

Comment (Tak) [reply app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt]: Ah right, good point @ view

File: app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt [hunk 5]
```diff
@@ -181,6 +182,25 @@ class SendStatusService : Service(), Injectable {
                 return@launch
             }
 
+            val isEditing = statusToSend.statusId != null
```
Comment (Tak) [inline app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt:185]: You could refactor the `createStatus`/`editStatus` block below to reuse this variable 🙂

File: app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt (hunk 1 above)
Comment (Lakoja) [reply app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt]: Probably not: This flow (its list) is observed by the activity.

However I made it a bit more clear: "AndGet" was never necessary here and "mediaValue" is actually a "mediaList".

File: app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt [hunk 6]
```diff
@@ -224,13 +224,13 @@ class ComposeActivity :
...
             onAddCaption = { item ->
-                CaptionDialog.newInstance(item.localId, item.description, item.uri)
-                    .show(supportFragmentManager, "caption_dialog")
+                CaptionDialog.newInstance(item.localId, item.description, item.uri).show(supportFragmentManager, "caption_dialog")
             },
             onAddFocus = { item ->
                 makeFocusDialog(item.focus, item.uri) { newFocus ->
                     viewModel.updateFocus(item.localId, newFocus)
                 }
+                // TODO this is inconsistent to CaptionDialog (device rotation)?
```
Comment (connyduck) [inline app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt:233]: ?

File: app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt [hunk 7]
```diff
@@ -181,6 +182,25 @@ class SendStatusService : Service(), Injectable {
...
+                media.forEach { mediaItem ->
+                    if (mediaItem.processed) {
+                        mastodonApi.updateMedia(mediaItem.id!!, mediaItem.description, mediaItem.focus?.toMastodonApiString())
+                            .fold({
+                            }, { throwable ->
+                                Toast.makeText(
+                                    applicationContext,
+                                    R.string.error_failed_set_caption,
+                                    Toast.LENGTH_SHORT
+                                ).show()
```
Comment (connyduck) [inline app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt:197]: Shouldn't it retry like it is done for all other failures? Or at least fail hard with a notification? Just showing a toast but continuing with posting the status is not what I would expect as a user

File: app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt (hunk 6 above)
Comment (Lakoja) [reply app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt:233]: There was a change/issue to make the text in the alt text dialog survive a device rotation.

This was not done to the focus dialog.

So one could change this as well (which is this todo).

File: app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt (hunk 7 above)
Comment (Lakoja) [reply app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt:197]: Hm, it was like this before. (which of course might not have been optimal, but probably outside of the scope of this issue?)

Also I thought it was ok because alt text and focus point are not the main concerns on a status with an image.

But I can of course give retry + fail a look.

Comment (connyduck) [reply app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt:197]: Yes please have a look, maybe it is easy to do. If not, this is still better than before and we can improve it later.

Comment (Lakoja) [reply app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt]: It uses now the same fail or retry logic as failures on the status send itself.

File: app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt [hunk 8]
```diff
@@ -290,6 +310,9 @@ class SendStatusService : Service(), Injectable {
             notificationManager.cancel(statusId)
             notificationManager.notify(errorNotificationId++, notification)
         }
+
+        // NOTE only this removes the "Sending..." notification (added with startForeground() above)
```
Comment (Lakoja) [inline app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt:314]: Another collateral fix. Otherwise the "Sending..." notification cannot be remove upon errors.

File: app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt [hunk 9]
```diff
@@ -244,18 +260,22 @@ class SendStatusService : Service(), Injectable {
...
         }
     }
 
+    private suspend fun failOrRetry(throwable: Throwable, statusId: Int) {
+        if (throwable is HttpException) {
+            // the server refused to accept, save status & show error message
+            failSending(statusId)
+        } else {
+            // a network problem occurred, let's retry sending the status
+            retrySending(statusId)
```
Comment (Lakoja) [inline app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt:275]: This would retry indefinitely? (retries are counted but I don't see a cancel?)

What kind of exceptions are network problems?

Comment (connyduck) [reply app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt:275]: Yes this retries until it is cancelled, the whole idea behind this construct is that status gets send once the device is connected again.

Network problem is everything that causes the call to fail before a server response (successfull or unsuccessfull) is received.

**Comment by Lakoja** [comment]
Regarding the current linter error:

> Error: "error_failed_set_caption" is translated here but not found in default locale

That is correct as I removed it.

Should/must I remove it from all others as well?
(Or is that done "automatically" once any translation is updated by a translator?)

**Comment by connyduck** [comment]
Once this is merged, Weblate should send a PR to remove it from everywhere, yes. But I can't merge because lint is complaining 🙄 
I could bypass the merge block, but I'd prefer it if you removed it everywhere.

**Comment by Lakoja** [comment]
> Should be good to go if you resolve the conflicts

Done.

It doesn't seem to be a good idea to remove / change things in other files than the default strings.xml.
That was a lot of work now.  And lots of conflicts repeatedly...
