### PR TITLE
fix compose notification action not recreating MainActivity

### LINKED ISSUE #4247: Opening Compose from Notification for Different Account Corrupts Timeline
I have two accounts setup on Tusky 24.1 and I accidentally hit "compose" instead of "quick reply" on a notification I had from the second account while the first was open in Tusky. This caused both the toot I was responding to and the toot I authred to show up in the wrong timeline.

The events happen as follows:
- Open Tusky to account A
- Open notification drawer
- Tap on "compose" for a notification from account B
- Compose and send toot
- Account A's timeline gets corrupted with content from account B

* * * *
- Tusky Version: 24.1
- Android Version: U
- Android Device: Pixel Fold
- Mastodon instance (if applicable):

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

### PR DESCRIPTION
**Pull request by connyduck**
closes #4247

### CODE REVIEW

File: app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java [hunk 1]
```diff
@@ -456,7 +456,7 @@ private static PendingIntent getStatusComposeIntent(Context context, Notificatio
 
         Intent composeIntent = MainActivity.composeIntent(context, composeOptions, account.getId(), body.getId(), (int)account.getId());
 
-        composeIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
+        composeIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
```
Comment (charlag) [inline app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java:459]: I'd leave a comment in code why we do this

**Review by charlag — APPROVED** [review]

File: app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java (hunk 1 above)
Comment (Tak) [reply app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java:459]: ➕

**Review by Tak — APPROVED** [review]
