### PR TITLE
Fix announcement reactions

### LINKED ISSUE #2308: Announcement reactions for custom emoji are oversized
Announcement reaction buttons for custom emoji are wider than regular emoji. Looks to me as if they're being sized according to the shortcode.

Pictured below: :chitter:, unicode bee, and :BigBlobhajHug: 

the first one is a little extra wide and the third one is very extra wide

* * * *
- Tusky Version: 15.1
- Android Version: 11
- Android Device: Poco X3
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

### PR DESCRIPTION
**Pull request by connyduck**
- closes #2308 
- fixes an issue that causes announcement reactions to not properly update when clicked

### CODE REVIEW

File: app/src/main/java/com/keylesspalace/tusky/components/announcements/AnnouncementAdapter.kt [hunk 1]
```diff
@@ -69,42 +72,38 @@ class AnnouncementAdapter(
...
+                        isCheckable = true
+                        checkedIcon = null
+                        chips.addView(this, i)
+                    }
+                )
+                .apply {
+                    if (reaction.url == null) {
+                        this.text = "${reaction.name} ${reaction.count}"
+                    } else {
+                        val spanBuilder = SpannableStringBuilder("E ${reaction.count}")
```
Comment (charlag) [inline app/src/main/java/com/keylesspalace/tusky/components/announcements/AnnouncementAdapter.kt:87]: I got confused by this `E` for quite a bit but then I realized it's for emoji. Why can't we put the emoji itself there? Do we know the name or shortcode? This might be better for the screen reader

Comment (connyduck) [reply app/src/main/java/com/keylesspalace/tusky/components/announcements/AnnouncementAdapter.kt:87]: Yes but putting the name there is what causes the sizing bug :/
Spans have a content description, maybe that's where the name should go? No idea what a screenreader does with it though.

Comment (charlag) [reply app/src/main/java/com/keylesspalace/tusky/components/announcements/AnnouncementAdapter.kt:87]: I think putting it on a span wouldn't hurt. Putting something that is usually not pronounced (like fixed-width space) instead of E could be good as well. Also a comment why we do any of this, otherwise next clueless person who touches this will break it.

**Comment by connyduck** [comment]
Meh, span content descriptions are API 30+ only. Still, better than before.

**Comment by Gipsysoftware** [comment]
I hope you will do the update is that the problem of playing the video is solved

**Review by charlag — APPROVED** [review]
