### PR TITLE
Show toast if pin fails

### LINKED ISSUE #2229: Error handling for pinning toots
Mastodon has a limit of five toots that can be pinned simultaneously. When another toot is pinned, the web app pops up a toast saying "422 Validation failed: You have already pinned the maximum number of toots". On Tusky, the action fails silently. Simply doing the same thing as the web app would solve this.

* * * *
- Tusky Version: 15.1
- Android Version: 12 beta
- Android Device: Pixel 4A 5G

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

### PR DESCRIPTION
**Pull request by evant**
Fixes #2229

### CODE REVIEW

**Review by thebino — APPROVED** [review]

**Comment by connyduck** [comment]
Can we have a snackbar instead of a toast?

**Comment by evant** [comment]
Done!

**Comment by connyduck** [comment]
Nice! What do you think about a generic "Failed to pin" message when we don't get one from the server? Also the exception should be logged.

**Comment by evant** [comment]
Makes sense. Added a generic error for cases where we don't have a server error.

File: app/src/main/java/com/keylesspalace/tusky/usecase/TimelineCases.kt [hunk 1]
```diff
@@ -130,6 +131,10 @@ class TimelineCases @Inject constructor(
     fun pin(statusId: String, pin: Boolean): Single<Status> {
         // Replace with extension method if we use RxKotlin
         return (if (pin) mastodonApi.pinStatus(statusId) else mastodonApi.unpinStatus(statusId))
+            .onErrorResumeNext(::convertError)
+            .doOnError { e ->
+                Log.w("Failed to pin", e)
```
Comment (thebino) [inline app/src/main/java/com/keylesspalace/tusky/usecase/TimelineCases.kt:136]: should the log reflect the action (pin/unpin)

Comment (connyduck) [reply app/src/main/java/com/keylesspalace/tusky/usecase/TimelineCases.kt:136]: Not necessarily. How about "Failed to change pin state"

Comment (evant) [reply app/src/main/java/com/keylesspalace/tusky/usecase/TimelineCases.kt]: Updated the message, also swapped it around to log the original error instead of the converted one since that's probably more useful.
