### PR TITLE
Add new Theme "Use System Design" + fixes to night mode

### LINKED ISSUE #671: forced UI theme bug in 8.1 Oreo
i started using the 8.1 Pixel Experience rom instead of MIUI 9 on my Xiaomi Redmi 4x phone, and before, i could toggle between the light and the dark UI from the app's settings. now the system's option overwrites Tusky's theme - i can change to dark or light UI from the Tusky settings, but nothing will happen, only when i change the overall theme in the Android settings. Screenshots: https://imgur.com/a/kW58g45

* * * *
- Tusky Version: 1.8.0
- Android Version: 8.1
- Android Device: Xiaomi Redmi 4X
- Mastodon instance (if applicable): mastodon.social

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

### PR DESCRIPTION
**Pull request by bernd289**
Adds Theme "Use System Design" because some devices can switch system design on a schedule.
As Example: https://www.xda-developers.com/samsung-galaxy-s9-update-night-mode-schedule/ 

+ Includes fixes from https://github.com/tuskyapp/Tusky/pull/1060 (also fixes #671)

I only found one Bug where I'm not sure how to fix:
When System is in dark mode, and I switch Tusky from light to "Use System Design" it stays in light mode.
If I now change System design to light and back to dark, Tusky switches also to dark theme.
Kill App and restart does also fix it.

Switching other Themes works just fine for me and without the mentioned bug.

### CODE REVIEW

**Comment by bernd289** [comment]
"Fixed" the mentioned bug with a workaround...

File: app/src/main/java/com/keylesspalace/tusky/PreferencesActivity.kt [hunk 1]
```diff
@@ -135,7 +136,13 @@ class PreferencesActivity : BaseActivity(), SharedPreferences.OnSharedPreference
                 finish()
                 overridePendingTransition(R.anim.fade_in, R.anim.fade_out)
 
-                restartActivitiesOnExit = true
+                // MODE_NIGHT_FOLLOW_SYSTEM workaround part 2 :/
+                when(theme){
+                    "auto_system" -> {
```
Comment (connyduck) [inline app/src/main/java/com/keylesspalace/tusky/PreferencesActivity.kt]: should use the constant from `ThemeUtils`

File: app/build.gradle [hunk 2]
```diff
@@ -82,7 +82,7 @@ dependencies {
         transitive = true
     }
     implementation 'androidx.core:core:1.0.1'
-    implementation 'androidx.appcompat:appcompat:1.0.2'
+    implementation 'androidx.appcompat:appcompat:1.1.0-alpha02'
```
Comment (connyduck) [inline app/build.gradle]: why the alpha version?

File: app/src/main/java/com/keylesspalace/tusky/util/ThemeUtils.java [hunk 3]
```diff
@@ -104,29 +99,30 @@ public static void setDrawableTint(Context context, Drawable drawable, @AttrRes
...
-        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
-            UiModeManager uiModeManager = (UiModeManager)context.getApplicationContext().getSystemService(Context.UI_MODE_SERVICE);
-            uiModeManager.setNightMode(mode);
-        } else {
-            AppCompatDelegate.setDefaultNightMode(mode);
+                //stupid workaround to make MODE_NIGHT_FOLLOW_SYSTEM work :(
+                if((Settings.System.getInt(context.getContentResolver(), "display_night_theme", 0) == 1)) {
+                    AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);
+                } else if ((Settings.System.getInt(context.getContentResolver(), "display_night_theme", 0) == 0)) {
+                    AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO);
```
Comment (connyduck) [inline app/src/main/java/com/keylesspalace/tusky/util/ThemeUtils.java]: Why does this work? If you switch the system theme, Tusky won't follow if you set anything other than `MODE_NIGHT_FOLLOW_SYSTEM` or what am I missing?

**Comment by connyduck** [comment]
Also we need to find a solution to fix the tests. 🤔

File: app/src/main/java/com/keylesspalace/tusky/util/ThemeUtils.java (hunk 3 above)
Comment (bernd289) [reply app/src/main/java/com/keylesspalace/tusky/util/ThemeUtils.java]: It then works because of workaround part 2 from there: https://github.com/tuskyapp/Tusky/pull/1069/files#r260898481

E.g. when switching from Tusky in Light theme (System is in Dark Theme) to Tusky in Auto theme it would stay in light until I switch System Theme to light and back to dark or kill the Tusky App and start it again, not sure if only Bug on Samsung S9 or whatever... That's why I check for system settings, set correct theme, apply it, then go back to auto theme, this way it works for me as expected. :/

Do you have a better suggestion there?

**Comment by bernd289** [comment]
> Is there a way to detect if an device does support the system mode?

Maybe if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) ?

But not sure. IIRC Huawei has also a night mode in Oreo Based Firmwares, at least on Mate 10 Pro.

**Comment by connyduck** [comment]
It seems Crowdin is messing with translation files. Can you please delete the german translation? We can translate it later via Crowdin.

But I think we can give this a try with nightly users.

**Comment by bernd289** [comment]
@connyduck translation updated

**Comment by connyduck** [comment]
oh damn, the tests 🤦‍♂️
We somehow need to mock the `AppCompatDelegate.setDefaultNightMode` or remove it from tests. I can have a look if you want.

**Comment by bernd289** [comment]
@connyduck yes, please take over the tests. I'm not sure how to fix that :/

**Comment by charlag** [comment]
Updating Robolectric wouldn't help? It must be a common thing.

**Comment by bernd289** [comment]
@charlag I already tried with roboelectric 4.2 and a very few other little changes regarding to tests and deps - did not work.
Currently I get this locally when running tests: https://pastebin.com/GF6ZJW0R
If you want I can push these changes - but they don't fix it :/

**Comment by charlag** [comment]
Maybe test resource then?...
-- 
Sincerely,
Ivan



4 Mar 2019, 22:55 by notifications@github.com:

**Comment by connyduck** [comment]
I sent a PR to your branch: https://github.com/bernd289/Tusky/pull/1

Basically what I did is making the method `ThemeUtils.setAppNightMode` non-static so its easily mockable

hope thats ok @charlag

**Comment by charlag** [comment]
Seems alright

**Comment by bernd289** [comment]
thank you @connyduck :)

**Comment by connyduck** [comment]
Tests are green, lets merge!
